apiVersion: v1
kind: Pod
metadata:
  name: readiness-missing-dependency-app
  labels:
    app: readiness-missing-dependency-app
spec:
  containers:
  - name: app
    image: kube-readiness-missing-dependency-app
    imagePullPolicy: Never
    ports:
    - containerPort: 8080
    readinessProbe:
      httpGet:
        path: /
        port: 8080
      initialDelaySeconds: 5
      periodSeconds: 5
      failureThreshold: 3
