apiVersion: v1
kind: Pod
metadata:
  labels:
    test: readiness
  name: readiness-http
spec:
  containers:
  - name: readiness
    image: registry.k8s.io/e2e-test-images/agnhost:2.40
    args:
    - netexec  # Valid subcommand: Starts always-healthy HTTP server
    - --http-port=8080  # Explicit port for the server
    ports:  # Optional but recommended for exposure
    - containerPort: 8080
    readinessProbe:
      httpGet:
        path: /invalid-path
        port: 8080
        httpHeaders:
        - name: Custom-Header
          value: Awesome
      initialDelaySeconds: 3
      periodSeconds: 3
