apiVersion: v1
kind: Pod
metadata:
  name: kube-missing-dependency
spec:
  containers:
  - name: kube-missing-dependency
    image: kube-missing-dependency-app:latest
    imagePullPolicy: Never
    ports:
        - containerPort: 8765
    command: ["python", "server.py"]
